apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-limiter-app
  template:
    metadata:
      labels:
        app: rate-limiter-app
    spec:
      containers:
      - name: rate-limiter-app
        image: nikaris/rate-limiter:latest
        ports:
        - containerPort: 5000
        env:
        - name: RATE_LIMIT
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: RATE_LIMIT
        - name: EXPIRE_TIME
          valueFrom:
            configMapKeyRef:
              name: environment-config
              key: EXPIRE_TIME
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: REDIS_HOST
        # for autoscalling
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 500Mi


